#!/bin/sh

bold="#ab4642"

Date() {
    date=$(date "+%d/%m/%Y")
    echo -n "%{F$bold}Date:%{F-} $date    "
}

Time() {
    time=$(date "+%X")
    echo -n "%{F$bold}Time:%{F-} $time    "
}

while true; do
    echo "%{c}$(Date)$(Time)"
    sleep 1;
done
